#!/bin/sh
#for d in 40 60 58 87 80 120 180 20 29 76 152 167 1024; do /Applications/Inkscape.app/Contents/Resources/bin/inkscape -e /Users/sstevano/Documents/my/src/Workspace/ViewPagerTest/app/src/alanFord/Icon$d.png -w $d -h $d /Users/sstevano/Documents/my/src/Workspace/ViewPagerTest/app/src/alanFord/Icon.svg; done
for d in 40 60 58 87 80 120 180 20 29 76 152 167 1024; do /Applications/Inkscape.app/Contents/MacOS/inkscape -o ./Icon$d.png -w $d -h $d /Users/sstevano/Documents/my/src/Workspace/ViewPagerTest/app/src/alanFord/Icon.svg; done
